# Generated by Django 6.0.3 on 2026-03-13 09:28

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = []

    operations = [VectorExtension()]
