# Generated by Django 6.0.3 on 2026-03-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("linuxfr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SitemapEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.URLField(unique=True)),
                ("last_modified", models.DateTimeField()),
                (
                    "change_frequency",
                    models.CharField(
                        choices=[
                            ("always", "Always"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("never", "Never"),
                        ],
                        max_length=20,
                    ),
                ),
                ("priority", models.FloatField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("news", "News"),
                            ("diary", "Diary"),
                            ("link", "Link"),
                            ("forum_post", "Forum Post"),
                            ("poll", "Poll"),
                            ("ticket", "Ticket"),
                            ("comment", "Comment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
