# Generated by Django 6.0.3 on 2026-03-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linuxfr", "0003_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=255, unique=True)),
                ("display_name", models.CharField(max_length=255)),
            ],
        ),
    ]
