# Generated by Django 6.0.3 on 2026-03-17 17:04

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linuxfr", "0004_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("news", "News"),
                            ("diary", "Diary"),
                            ("link", "Link"),
                            ("forum_post", "Forum Post"),
                            ("poll", "Poll"),
                            ("ticket", "Ticket"),
                            ("comment", "Comment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("score", models.IntegerField()),
                ("content", models.TextField()),
                ("published_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="linuxfr.profile",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_nodes",
                        related_query_name="content_nodes",
                        to="linuxfr.page",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        related_query_name="child",
                        to="linuxfr.contentnode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentNodeEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vector", pgvector.django.vector.VectorField(dimensions=1024)),
                ("generated_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_node",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        related_query_name="embedding",
                        to="linuxfr.contentnode",
                    ),
                ),
            ],
        ),
    ]
