# Generated by Django 6.0.3 on 2026-03-13 16:02

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("linuxfr", "0005_contentnode"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentnode",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1024, null=True
            ),
        ),
    ]
