# Generated by Django 6.0.3 on 2026-03-15 12:36

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


def forward_func(apps, schema_editor):
    ContentNode = apps.get_model("linuxfr", "ContentNode")
    ContentNodeEmbedding = apps.get_model("linuxfr", "ContentNodeEmbedding")

    for content_node in ContentNode.objects.filter(embedding__isnull=False):
        embedding_instance = ContentNodeEmbedding.objects.create(
            content_node=content_node,
            vector=content_node.old_embedding,
        )
        embedding_instance.save()


def reverse_func(apps, schema_editor):
    ContentNodeEmbedding = apps.get_model("linuxfr", "ContentNodeEmbedding")

    for embedding in ContentNodeEmbedding.objects.all():
        content_node = embedding.content_node
        content_node.old_embedding = embedding.vector
        content_node.save()


class Migration(migrations.Migration):
    dependencies = [
        ("linuxfr", "0006_contentnode_embedding"),
    ]

    operations = [
        migrations.RenameField("contentnode", "embedding", "old_embedding"),
        migrations.CreateModel(
            name="ContentNodeEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vector", pgvector.django.vector.VectorField(dimensions=1024)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_node",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        related_query_name="embedding",
                        to="linuxfr.contentnode",
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            code=forward_func,
            reverse_code=reverse_func,
        ),
        migrations.RemoveField(
            model_name="contentnode",
            name="old_embedding",
        ),
    ]
