[project]
name = "lfr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "hishel[httpx]>=1.1.9",
    "ipykernel>=7.2.0",
    "ipython>=9.11.0",
    "lxml>=6.0.2",
    "nbformat>=5.10.4",
    "plotly[express]>=6.6.0",
    "polars>=1.39.0",
    "pyarrow>=23.0.1",
    "tqdm>=4.67.3",
]

[project.scripts]
lfr_import_content = "lfr.commands.import_content:main"
lfr_update_pages = "lfr.commands.update_pages:main"
lfr_update_profiles = "lfr.commands.update_profiles:main"
lfr_update_sitemap = "lfr.commands.update_sitemap:main"
[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"
