# Generated by Django 6.0.3 on 2026-03-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("last_modified", models.DateTimeField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("news", "News"),
                            ("diary", "Diary"),
                            ("link", "Link"),
                            ("forum_post", "Forum Post"),
                            ("poll", "Poll"),
                            ("ticket", "Ticket"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
