# Generated by Django 6.0.3 on 2026-03-12 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linuxfr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("html", models.TextField()),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content",
                        related_query_name="content",
                        to="linuxfr.page",
                    ),
                ),
            ],
        ),
    ]
